#!/bin/bash

if ! command -v maim >/dev/null 2>&1 && 
   ! command -v xclip >/dev/null 2>&1 &&
   ! command -v xdotool >/dev/null 2>&1; then
  echo "Dependencies not installed"
  echo "Make sure that the following programs are installed:"
  echo "- maim"
  echo "- xclip"
  echo "- xdotool"

  exit 1
fi

echo -e "Setting environment variables\n"
curl -s https://raw.githubusercontent.com/PhilippThaler/i3-screenshot-mode/master/config

echo -e "Downloading the i3-mode from GitHub\n"
echo $I3CONFIG

echo -e "\n\n\n" >> $I3CONFIG
curl -s https://raw.githubusercontent.com/PhilippThaler/i3-screenshot-mode/master/screenshot-mode >> $I3CONFIG
